apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base/backend
  - ../../base/gotenberg
  - gotenberg-allow-sandbox-networkpolicy.yaml

patches:
  - path: backend-hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: backend
  - path: httproute-host-patch.yaml
    target:
      kind: HTTPRoute
      name: backend
