-- TABLE
CREATE TABLE IF NOT EXISTS "public"."documents" (
    "id" INTEGER NOT NULL,
    "owned_by_user_id" "uuid",
    "source_url" "text" NOT NULL,
    "source_type" "text" NOT NULL,
    "file_name" "text",
    "file_checksum" "text",
    "file_size" INTEGER,
    "num_pages" INTEGER,
    "folder_id" INTEGER,
    "processing_finished_at" TIMESTAMP WITH TIME ZONE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" (),
    "access_group_id" "uuid",
    "uploaded_by_user_id" "uuid",
    CONSTRAINT "chk_documents_ownership" CHECK (
        (
            (
                ("owned_by_user_id" IS NOT NULL)
                AND ("access_group_id" IS NULL)
            )
            OR (
                ("owned_by_user_id" IS NULL)
                AND ("access_group_id" IS NOT NULL)
            )
        )
    )
);

ALTER TABLE "public"."documents" OWNER TO "postgres";

ALTER TABLE "public"."documents"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."documents_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY "public"."documents"
ADD CONSTRAINT "documents_pkey" PRIMARY KEY ("id");

CREATE INDEX "idx_documents_owned_by_user_id" ON "public"."documents" USING "btree" ("owned_by_user_id");

CREATE INDEX "idx_documents_source_type" ON "public"."documents" USING "btree" ("source_type");

-- FOREIGN KEYS
ALTER TABLE ONLY "public"."documents"
ADD CONSTRAINT "documents_access_group_id_fkey" FOREIGN KEY ("access_group_id") REFERENCES "public"."access_groups" ("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."documents"
ADD CONSTRAINT "documents_owner_user_id_fkey" FOREIGN KEY ("owned_by_user_id") REFERENCES "auth"."users" ("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."documents"
ADD CONSTRAINT "documents_uploaded_by_user_id_fkey" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "auth"."users" ("id") ON DELETE SET NULL;

-- RLS POLICIES
ALTER TABLE "public"."documents" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to insert documents" ON "public"."documents" FOR INSERT TO "authenticated"
WITH
    CHECK (
        (
            (
                (
                    "owned_by_user_id" = (
                        SELECT
                            "auth"."uid" () AS "uid"
                    )
                )
                AND (NOT "public"."is_current_user_banned" ())
            )
            OR (
                "public"."is_application_admin" ()
                AND ("owned_by_user_id" IS NULL)
            )
        )
    );

CREATE POLICY "Allow authenticated users to read documents" ON "public"."documents" FOR
SELECT
    TO "authenticated" USING (
        (
            (
                ("owned_by_user_id" IS NULL)
                OR (
                    "owned_by_user_id" = (
                        SELECT
                            "auth"."uid" () AS "uid"
                    )
                )
            )
            AND (NOT "public"."is_current_user_banned" ())
        )
    );

CREATE POLICY "Allow authenticated users to update documents" ON "public"."documents"
FOR UPDATE
    TO "authenticated" USING (
        (
            (
                "owned_by_user_id" = (
                    SELECT
                        "auth"."uid" () AS "uid"
                )
            )
            AND (NOT "public"."is_current_user_banned" ())
        )
    );

CREATE POLICY "Allow owners to delete documents and admins to delete base know" ON "public"."documents" FOR DELETE TO "authenticated" USING (
    (
        (
            (
                (
                    "owned_by_user_id" = (
                        SELECT
                            "auth"."uid" () AS "uid"
                    )
                )
                AND (NOT "public"."is_current_user_banned" ())
            )
            OR (
                "public"."is_application_admin" ()
                AND ("owned_by_user_id" IS NULL)
            )
        )
        AND ("source_type" <> 'default_document'::"text")
    )
);

GRANT ALL ON TABLE "public"."documents" TO "anon";

GRANT ALL ON TABLE "public"."documents" TO "authenticated";

GRANT ALL ON TABLE "public"."documents" TO "service_role";

GRANT ALL ON SEQUENCE "public"."documents_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."documents_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."documents_id_seq" TO "service_role";
