CREATE EXTENSION if NOT EXISTS "vector"
WITH
	schema "extensions";

CREATE EXTENSION if NOT EXISTS "pg_jsonschema"
WITH
	schema "extensions";

CREATE TABLE "public"."registered_documents" (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owned_by_user_id UUID DEFAULT NULL,
	"source_url" TEXT NOT NULL,
	"source_type" TEXT NOT NULL,
	"registered_at" TIMESTAMPTZ NOT NULL,
	"metadata" JSONB
);

CREATE TABLE "public"."processed_documents" (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owned_by_user_id UUID DEFAULT NULL,
	"file_checksum" TEXT NOT NULL,
	"file_size" int4 NOT NULL,
	"num_pages" int4 NOT NULL,
	"processing_started_at" TIMESTAMPTZ,
	"processing_finished_at" TIMESTAMPTZ,
	"processing_error" TEXT,
	"registered_document_id" int4,
	CONSTRAINT "processed_documents_registered_document_id_fkey" FOREIGN key ("registered_document_id") REFERENCES "public"."registered_documents" ("id") ON DELETE CASCADE
);

CREATE TABLE "public"."processed_document_summaries" (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owned_by_user_id UUID DEFAULT NULL,
	"summary" TEXT NOT NULL,
	"summary_embedding_temp" vector,
	"tags" _text NOT NULL,
	"processed_document_id" int4,
	"summary_embedding" vector NOT NULL,
	"summary_temp" TEXT,
	"tags_temp" _text,
	CONSTRAINT "processed_document_summaries_processed_document_id_fkey" FOREIGN key ("processed_document_id") REFERENCES "public"."processed_documents" ("id") ON DELETE CASCADE
);

CREATE TABLE "public"."processed_document_chunks" (
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owned_by_user_id UUID DEFAULT NULL,
	"content" TEXT NOT NULL,
	"embedding_temp" vector,
	"page" int4 NOT NULL,
	"chunk_index" int4 NOT NULL,
	"processed_document_id" int4,
	"embedding" vector NOT NULL,
	"content_temp" TEXT,
	CONSTRAINT "processed_document_chunks_processed_document_id_fkey" FOREIGN key ("processed_document_id") REFERENCES "public"."processed_documents" ("id") ON DELETE CASCADE
);

-- This script only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.
-- Sequence and defined type
CREATE SEQUENCE if NOT EXISTS user_requests_id_seq;

-- Table Definition
CREATE TABLE "public"."user_requests" (
	"created_at" TIMESTAMP NOT NULL,
	"request_payload" JSON NOT NULL CHECK (
		json_matches_schema (
			'{
	"type": "object",
	"properties": {
		"query": {
			"type": "string"
		},
		"match_threshold": {
			"type": "number"
		},
		"num_probes_chunks": {
			"type": "number"
		},
		"num_probes_summaries": {
			"type": "number"
		},
		"search_algorithm": {
			"type": "string"
		},
		"chunk_limit": {
			"type": "number"
		},
		"summary_limit": {
			"type": "number"
		},
		"document_limit": {
			"type": "number"
		}
	}
}'::JSON,
			request_payload
		)
	),
	"question" TEXT NOT NULL,
	"generated_answer" TEXT,
	"error" TEXT,
	"llm_model" TEXT NOT NULL,
	"llm_embedding_model" TEXT NOT NULL,
	"matching_documents" JSON NOT NULL CHECK (
		json_matches_schema (
			'{
	"type": "array",
	"items": {
		"type": "object",
		"properties": {
			"registered_document_id": { "type": "number" },
			"processed_document_id": { "type": "number" },
            "similarity": { "type": "number" },
			"processed_document_summary_match": {
				"type": "object",
				"properties": {
					"processed_document_summary_id": { "type": "number" },
					"processed_document_summary_similarity": { "type": "number" }
				}
			},
			"processed_document_chunk_matches": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"processed_document_chunk_id": { "type": "number" },
						"processed_document_chunk_similarity": { "type": "number" }
					}
				}
			}
		}
	}
}'::JSON,
			matching_documents
		)
	),
	"short_id" TEXT,
	"id" int8 NOT NULL DEFAULT NEXTVAL('user_requests_id_seq'::regclass),
	"moderation_time_ms" int4,
	"embedding_time_ms" int4,
	"database_search_time_ms" int4,
	"chat_completion_time_ms" int4,
	"summary_ids_in_context" _int4,
	"chunk_ids_in_context" _int4
);

CREATE OR REPLACE FUNCTION generate_short_id () returns trigger AS $$
BEGIN
  NEW.short_id := id_encode(NEW.id);
  RETURN NEW;
END;
$$ language plpgsql;

CREATE OR REPLACE TRIGGER trigger_on_insert_user_requests before insert ON user_requests FOR each ROW
EXECUTE function generate_short_id ();
