-- create new unified document table
CREATE TABLE IF NOT EXISTS documents (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	owned_by_user_id UUID DEFAULT NULL,
	source_url TEXT NOT NULL,
	source_type TEXT NOT NULL,
	file_name TEXT,
	file_checksum TEXT,
	file_size INT,
	num_pages INT,
	folder_id INT DEFAULT NULL,
	processing_finished_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migrate existing recorded documents into unified documents table
INSERT INTO
	documents (
		id,
		owned_by_user_id,
		source_url,
		source_type,
		file_name,
		file_checksum,
		file_size,
		num_pages,
		folder_id,
		processing_finished_at,
		created_at
	)
SELECT
	pd.id,
	pd.owned_by_user_id,
	rd.source_url,
	rd.source_type,
	rd.filename,
	pd.file_checksum,
	pd.file_size,
	pd.num_pages,
	rd.folder_id,
	pd.processing_finished_at,
	rd.registered_at
FROM
	processed_documents pd
	JOIN registered_documents rd ON pd.registered_document_id = rd.id;

-- Rename tables for summaries and chunks
ALTER TABLE processed_document_summaries
RENAME TO document_summaries;

ALTER TABLE processed_document_chunks
RENAME TO document_chunks;

-- Rename foreign key columns to document_id
ALTER TABLE document_summaries
RENAME COLUMN processed_document_id TO document_id;

ALTER TABLE document_chunks
RENAME COLUMN processed_document_id TO document_id;

-- Point foreign keys to unified documents
ALTER TABLE document_summaries
ADD CONSTRAINT document_summaries_document_id_fkey FOREIGN key (document_id) REFERENCES documents (id) ON DELETE CASCADE;

ALTER TABLE document_chunks
ADD CONSTRAINT document_chunks_document_id_fkey FOREIGN key (document_id) REFERENCES documents (id) ON DELETE CASCADE;

-- Update indexes for renamed columns
CREATE INDEX if NOT EXISTS idx_document_summaries_document_id ON document_summaries (document_id);

CREATE INDEX if NOT EXISTS idx_document_chunks_document_id ON document_chunks (document_id);

-- Drop legacy tables now migrated (with cascade to remove dependencies)
DROP TABLE IF EXISTS processed_documents cascade;

DROP TABLE IF EXISTS registered_documents cascade;

-- Update chat_messages triggers to fire on unified documents
CREATE TRIGGER trg_maintain_chat_messages_document_references before delete ON documents FOR each ROW
EXECUTE function maintain_chat_messages_document_references ();

-- Enable RLS and policies on new documents table
ALTER TABLE documents enable ROW level security;

CREATE POLICY "Allow authenticated users to read documents" ON documents FOR
SELECT
	TO authenticated USING (
		owned_by_user_id IS NULL
		OR owned_by_user_id = (
			SELECT
				auth.uid ()
		)
	);

CREATE POLICY "Allow authenticated users to insert documents" ON documents FOR insert TO authenticated
WITH
	CHECK (
		owned_by_user_id = (
			SELECT
				auth.uid ()
		)
	);

CREATE POLICY "Allow authenticated users to update documents" ON documents
FOR UPDATE
	TO authenticated USING (
		owned_by_user_id = (
			SELECT
				auth.uid ()
		)
	);

CREATE POLICY "Allow authenticated users to delete documents" ON documents FOR delete TO authenticated USING (
	owned_by_user_id = (
		SELECT
			auth.uid ()
	)
);

-- Enable RLS and policies on document_summaries
ALTER TABLE document_summaries enable ROW level security;

CREATE POLICY "Allow authenticated users to read document_summaries" ON document_summaries FOR
SELECT
	TO authenticated USING (
		owned_by_user_id IS NULL
		OR owned_by_user_id = (
			SELECT
				auth.uid ()
		)
	);

CREATE POLICY "Allow authenticated users to insert document_summaries" ON document_summaries FOR insert TO authenticated
WITH
	CHECK (
		owned_by_user_id = (
			SELECT
				auth.uid ()
		)
	);

CREATE POLICY "Allow authenticated users to update document_summaries" ON document_summaries
FOR UPDATE
	TO authenticated USING (
		owned_by_user_id = (
			SELECT
				auth.uid ()
		)
	);

CREATE POLICY "Allow authenticated users to delete document_summaries" ON document_summaries FOR delete TO authenticated USING (
	owned_by_user_id = (
		SELECT
			auth.uid ()
	)
);

-- Enable RLS and policies on document_chunks
ALTER TABLE document_chunks enable ROW level security;

CREATE POLICY "Allow authenticated users to read document_chunks" ON document_chunks FOR
SELECT
	TO authenticated USING (
		owned_by_user_id IS NULL
		OR owned_by_user_id = (
			SELECT
				auth.uid ()
		)
	);

CREATE POLICY "Allow authenticated users to insert document_chunks" ON document_chunks FOR insert TO authenticated
WITH
	CHECK (
		owned_by_user_id = (
			SELECT
				auth.uid ()
		)
	);

CREATE POLICY "Allow authenticated users to update document_chunks" ON document_chunks
FOR UPDATE
	TO authenticated USING (
		owned_by_user_id = (
			SELECT
				auth.uid ()
		)
	);

CREATE POLICY "Allow authenticated users to delete document_chunks" ON document_chunks FOR delete TO authenticated USING (
	owned_by_user_id = (
		SELECT
			auth.uid ()
	)
);

-- Drop legacy find_unprocessed_registered_documents and add new function for unified table
DROP FUNCTION if EXISTS public.find_unprocessed_registered_documents ();

CREATE OR REPLACE FUNCTION public.find_unprocessed_documents () returns TABLE (
	id INTEGER,
	owned_by_user_id UUID,
	source_url TEXT,
	source_type TEXT,
	file_name TEXT,
	file_checksum TEXT,
	file_size INT,
	num_pages INT,
	folder_id INT,
	processing_finished_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ
) language sql stable AS $$
    SELECT id, owned_by_user_id, source_url, source_type, file_name, file_checksum, file_size, num_pages, folder_id, processing_finished_at, created_at
      FROM documents
     WHERE processing_finished_at IS NULL;
  $$;

-- Drop legacy functions for matching documents and summaries
DROP FUNCTION if EXISTS public.match_document_chunks;

DROP FUNCTION if EXISTS public.match_summaries;

DROP FUNCTION if EXISTS public.match_summaries_and_chunks;

-- Recreate Jina search functions against unified tables and renamed columns
DROP FUNCTION if EXISTS public.match_jina_document_chunks;

CREATE OR REPLACE FUNCTION public.match_jina_document_chunks (
	query_embedding vector,
	match_threshold DOUBLE PRECISION,
	match_count INTEGER,
	num_probes INTEGER,
	user_id UUID,
	search_type TEXT,
	allowed_document_ids INTEGER[],
	allowed_folder_id INTEGER[] DEFAULT NULL
) returns TABLE (
	id INTEGER,
	document_id INTEGER,
	content TEXT,
	similarity DOUBLE PRECISION
) language plpgsql AS $$
BEGIN
  EXECUTE format('SET LOCAL ivfflat.probes = %s', num_probes);
  RETURN QUERY
  SELECT dc.id, dc.document_id, dc.content, (dc.chunk_jina_embedding <#> query_embedding)*-1 AS similarity
  FROM document_chunks dc
  WHERE ((search_type='favorites' AND dc.document_id=ANY(allowed_document_ids)) OR (search_type='all_private' AND dc.owned_by_user_id=user_id)
    OR (search_type='private_folder' AND dc.owned_by_user_id=user_id AND dc.folder_id=ANY(allowed_folder_id))
    OR (search_type='public_only' AND dc.owned_by_user_id IS NULL))
    AND (dc.chunk_jina_embedding <#> query_embedding)*-1>match_threshold
  ORDER BY dc.chunk_jina_embedding<#>query_embedding LIMIT match_count;
END;
$$;

DROP FUNCTION if EXISTS public.match_jina_summaries;

CREATE OR REPLACE FUNCTION public.match_jina_summaries (
	query_embedding vector,
	match_threshold DOUBLE PRECISION,
	match_count INTEGER,
	num_probes INTEGER,
	user_id UUID,
	search_type TEXT,
	allowed_document_ids INTEGER[],
	allowed_folder_ids INTEGER[] DEFAULT NULL
) returns TABLE (
	id INTEGER,
	document_id INTEGER,
	summary TEXT,
	similarity DOUBLE PRECISION
) language plpgsql AS $$
BEGIN
  EXECUTE format('SET LOCAL ivfflat.probes = %s', num_probes);
  RETURN QUERY
  SELECT ds.id, ds.document_id, ds.summary, (ds.summary_jina_embedding <#> query_embedding)*-1 AS similarity
  FROM document_summaries ds
  WHERE ((search_type='favorites' AND ds.document_id=ANY(allowed_document_ids)) OR (search_type='all_private' AND ds.owned_by_user_id=user_id)
    OR (search_type='private_folder' AND ds.owned_by_user_id=user_id AND ds.folder_id=ANY(allowed_folder_ids))
    OR (search_type='public_only' AND ds.owned_by_user_id IS NULL))
    AND (ds.summary_jina_embedding <#> query_embedding)*-1>match_threshold
  ORDER BY ds.summary_jina_embedding<#>query_embedding LIMIT match_count;
END;
$$;

DROP FUNCTION if EXISTS public.match_jina_summaries_and_chunks;

CREATE OR REPLACE FUNCTION public.match_jina_summaries_and_chunks (
	query_embedding vector,
	match_threshold DOUBLE PRECISION,
	chunk_limit INTEGER,
	summary_limit INTEGER,
	num_probes_chunks INTEGER,
	num_probes_summaries INTEGER,
	user_id UUID,
	allowed_document_ids INTEGER[],
	search_type TEXT,
	allowed_folder_ids INTEGER[] DEFAULT NULL
) returns TABLE (
	document_id INTEGER,
	chunk_ids INTEGER[],
	chunk_similarities DOUBLE PRECISION[],
	avg_chunk_similarity DOUBLE PRECISION,
	summary_ids INTEGER[],
	summary_similarity DOUBLE PRECISION,
	similarity DOUBLE PRECISION
) language plpgsql AS $$
BEGIN
  RETURN QUERY WITH chunk_winners AS (
    SELECT cw.id AS chunk_id, NULL::integer AS summary_id, cw.document_id, cw.similarity
    FROM match_jina_document_chunks(query_embedding,match_threshold,chunk_limit,num_probes_chunks,user_id,search_type,allowed_document_ids,allowed_folder_ids) cw
  ), summary_winners AS (
    SELECT NULL::integer AS chunk_id, sw.id AS summary_id, sw.document_id, sw.similarity
    FROM match_jina_summaries(query_embedding,match_threshold,summary_limit,num_probes_summaries,user_id,search_type,allowed_document_ids,allowed_folder_ids) sw
  ), all_winners AS (
    SELECT * FROM chunk_winners UNION ALL SELECT * FROM summary_winners
  )
  SELECT winners.document_id, ARRAY_AGG(winners.chunk_id) FILTER(WHERE winners.chunk_id IS NOT NULL),
    ARRAY_AGG(winners.similarity) FILTER(WHERE winners.chunk_id IS NOT NULL), AVG(winners.similarity) FILTER(WHERE winners.chunk_id IS NOT NULL),
    ARRAY_AGG(winners.summary_id) FILTER(WHERE winners.summary_id IS NOT NULL), AVG(winners.similarity) FILTER(WHERE winners.summary_id IS NOT NULL),
    CASE WHEN COUNT(winners.chunk_id)=0 THEN COALESCE(AVG(winners.similarity) FILTER(WHERE winners.summary_id IS NOT NULL),0)
      WHEN COUNT(winners.summary_id)=0 THEN COALESCE(AVG(winners.similarity) FILTER(WHERE winners.chunk_id IS NOT NULL),0)
      ELSE (COALESCE(AVG(winners.similarity) FILTER(WHERE winners.chunk_id IS NOT NULL),0)+COALESCE(AVG(winners.similarity) FILTER(WHERE winners.summary_id IS NOT NULL),0))/2 END
    AS similarity
  FROM all_winners winners GROUP BY winners.document_id ORDER BY similarity DESC;
END;
$$;
