ALTER TABLE public.profiles
DROP COLUMN is_admin;

-- Create a table to store user roles
CREATE TABLE public.application_admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL UNIQUE
);

comment ON TABLE public.application_admins IS 'Application admins to manage users via the dashboard.';

-- Enable row level security on the user_roles table
ALTER TABLE public.application_admins enable ROW level security;

-- Create a function to check if the current user is an application admin
CREATE OR REPLACE FUNCTION public.is_application_admin () returns BOOLEAN language sql security definer AS $$
select exists (
    select 1
    from public.application_admins
    where user_id = auth.uid()
);
$$;
