CREATE EXTENSION IF NOT EXISTS vector
WITH
    SCHEMA extensions;

CREATE EXTENSION IF NOT EXISTS pgcrypto
WITH
    SCHEMA extensions;

CREATE EXTENSION IF NOT EXISTS pg_trgm
WITH
    SCHEMA extensions;

CREATE EXTENSION IF NOT EXISTS pg_cron
WITH
    SCHEMA pg_catalog;

CREATE EXTENSION IF NOT EXISTS pg_jsonschema
WITH
    SCHEMA extensions;
