CREATE TABLE IF NOT EXISTS "public"."application_admins" ("id" BIGINT NOT NULL, "user_id" "uuid" NOT NULL);

ALTER TABLE "public"."application_admins" OWNER TO "postgres";

COMMENT ON TABLE "public"."application_admins" IS 'Application admins to manage users via the dashboard.';

ALTER TABLE "public"."application_admins"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."application_admins_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY "public"."application_admins"
ADD CONSTRAINT "application_admins_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."application_admins"
ADD CONSTRAINT "application_admins_user_id_key" UNIQUE ("user_id");

GRANT ALL ON TABLE "public"."application_admins" TO "anon";

GRANT ALL ON TABLE "public"."application_admins" TO "authenticated";

GRANT ALL ON TABLE "public"."application_admins" TO "service_role";

GRANT ALL ON SEQUENCE "public"."application_admins_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."application_admins_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."application_admins_id_seq" TO "service_role";
