CREATE TABLE IF NOT EXISTS "public"."document_chunks" (
    "id" INTEGER NOT NULL,
    "owned_by_user_id" "uuid",
    "content" "text" NOT NULL,
    "page" INTEGER NOT NULL,
    "chunk_index" INTEGER NOT NULL,
    "document_id" INTEGER,
    "folder_id" INTEGER,
    "full_text_search" "tsvector" GENERATED ALWAYS AS ("to_tsvector" ('"german"'::"regconfig", "content")) STORED,
    "access_group_id" "uuid",
    "chunk_mistral_embedding" "extensions"."vector" (1024),
    CONSTRAINT "chk_document_chunks_ownership" CHECK (
        (
            (
                ("owned_by_user_id" IS NOT NULL)
                AND ("access_group_id" IS NULL)
            )
            OR (
                ("owned_by_user_id" IS NULL)
                AND ("access_group_id" IS NOT NULL)
            )
        )
    )
);

ALTER TABLE "public"."document_chunks" OWNER TO "postgres";

ALTER TABLE "public"."document_chunks"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."processed_document_chunks_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY "public"."document_chunks"
ADD CONSTRAINT "processed_document_chunks_pkey" PRIMARY KEY ("id");

CREATE INDEX "idx_document_chunks_document_id" ON "public"."document_chunks" USING "btree" ("document_id");

CREATE INDEX "idx_document_chunks_full_text_search" ON "public"."document_chunks" USING "gin" ("full_text_search");

CREATE INDEX "idx_document_chunks_owned_by_user_id" ON "public"."document_chunks" USING "btree" ("owned_by_user_id");

GRANT ALL ON TABLE "public"."document_chunks" TO "anon";

GRANT ALL ON TABLE "public"."document_chunks" TO "authenticated";

GRANT ALL ON TABLE "public"."document_chunks" TO "service_role";

GRANT ALL ON SEQUENCE "public"."processed_document_chunks_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."processed_document_chunks_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."processed_document_chunks_id_seq" TO "service_role";
