CREATE TABLE IF NOT EXISTS "public"."document_summaries" (
    "id" INTEGER NOT NULL,
    "owned_by_user_id" "uuid",
    "summary" "text" NOT NULL,
    "tags" "text" [] NOT NULL,
    "document_id" INTEGER,
    "short_summary" "text",
    "folder_id" INTEGER,
    "summary_jina_embedding" "extensions"."vector" (1024),
    "access_group_id" "uuid",
    CONSTRAINT "chk_document_summaries_ownership" CHECK (
        (
            (
                ("owned_by_user_id" IS NOT NULL)
                AND ("access_group_id" IS NULL)
            )
            OR (
                ("owned_by_user_id" IS NULL)
                AND ("access_group_id" IS NOT NULL)
            )
        )
    )
);

ALTER TABLE "public"."document_summaries" OWNER TO "postgres";

ALTER TABLE "public"."document_summaries"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."processed_document_summaries_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY "public"."document_summaries"
ADD CONSTRAINT "processed_document_summaries_pkey" PRIMARY KEY ("id");

CREATE INDEX "idx_document_summaries_document_id" ON "public"."document_summaries" USING "btree" ("document_id");

CREATE INDEX "idx_document_summaries_owned_by_user_id" ON "public"."document_summaries" USING "btree" ("owned_by_user_id");

GRANT ALL ON TABLE "public"."document_summaries" TO "anon";

GRANT ALL ON TABLE "public"."document_summaries" TO "authenticated";

GRANT ALL ON TABLE "public"."document_summaries" TO "service_role";

GRANT ALL ON SEQUENCE "public"."processed_document_summaries_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."processed_document_summaries_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."processed_document_summaries_id_seq" TO "service_role";
