CREATE TABLE IF NOT EXISTS "public"."documents" (
    "id" INTEGER NOT NULL,
    "owned_by_user_id" "uuid",
    "source_url" "text" NOT NULL,
    "source_type" "text" NOT NULL,
    "file_name" "text",
    "file_checksum" "text",
    "file_size" INTEGER,
    "num_pages" INTEGER,
    "folder_id" INTEGER,
    "processing_finished_at" TIMESTAMP WITH TIME ZONE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT "now" (),
    "access_group_id" "uuid",
    "uploaded_by_user_id" "uuid",
    CONSTRAINT "chk_documents_ownership" CHECK (
        (
            (
                ("owned_by_user_id" IS NOT NULL)
                AND ("access_group_id" IS NULL)
            )
            OR (
                ("owned_by_user_id" IS NULL)
                AND ("access_group_id" IS NOT NULL)
            )
        )
    )
);

ALTER TABLE "public"."documents" OWNER TO "postgres";

ALTER TABLE "public"."documents"
ALTER COLUMN "id"
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."documents_id_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY "public"."documents"
ADD CONSTRAINT "documents_pkey" PRIMARY KEY ("id");

CREATE INDEX "idx_documents_owned_by_user_id" ON "public"."documents" USING "btree" ("owned_by_user_id");

CREATE INDEX "idx_documents_source_type" ON "public"."documents" USING "btree" ("source_type");

CREATE OR REPLACE TRIGGER "trg_maintain_chat_messages_document_references"
BEFORE DELETE ON "public"."documents" FOR EACH ROW
EXECUTE FUNCTION "public"."maintain_chat_messages_document_references" ();

CREATE OR REPLACE TRIGGER "trg_update_folder_id_cascading"
AFTER UPDATE OF "folder_id" ON "public"."documents" FOR EACH ROW WHEN (("old"."folder_id" IS DISTINCT FROM "new"."folder_id"))
EXECUTE FUNCTION "public"."update_folder_id_cascading" ();

GRANT ALL ON TABLE "public"."documents" TO "anon";

GRANT ALL ON TABLE "public"."documents" TO "authenticated";

GRANT ALL ON TABLE "public"."documents" TO "service_role";

GRANT ALL ON SEQUENCE "public"."documents_id_seq" TO "anon";

GRANT ALL ON SEQUENCE "public"."documents_id_seq" TO "authenticated";

GRANT ALL ON SEQUENCE "public"."documents_id_seq" TO "service_role";
