apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base/backend
  - ../../base/gotenberg

patches:
  - path: backend-hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: backend
  - path: gotenberg-hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: gotenberg
  - path: httproute-host-patch.yaml
    target:
      kind: HTTPRoute
      name: backend
