name: Backend Tests

on:
  pull_request:
    branches: [main, staging]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ⬇️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0, pinned to commit sha to avoid sha-hulud like attacks

      - name: Setup environment ⚙️
        uses: ./.github/actions/setup
        with:
          start-supabase: "true"
          install-1password: "true"

      - name: Fetch backend .env from 1Password ⬇️
        run: |
          cd apps/backend
          echo "Fetching backend .env from 1Password..."
          op read "op://${{ secrets.OP_VAULT_ID }}/${{ secrets.OP_BACKEND_TEST_ENV_ITEM_ID }}/notesPlain" > .env
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Wait for Supabase to be ready ⏳
        uses: ./.github/actions/wait-for-supabase

      - name: Run Database Linting 🔍
        run: |
          cd apps/backend
          npm run lint:db

      - name: Upload default document 📄
        run: |
          cd apps/backend
          npm run db:upload-default-documents

      - name: Run integration tests 🧪
        run: |
          cd apps/backend
          npm test
