name: prettier-eslint.yml
on:
  pull_request:
    branches: [main, staging]

jobs:
  prettier-eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ⬇️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0, pinned to commit sha to avoid sha-hulud like attacks

      - name: Setup environment ⚙️
        uses: ./.github/actions/setup

      - name: Check Prettier 🧹
        run: npm run prettier:check

      - name: Check ESLint 🔎
        run: npm run lint:check
